# Knowledge Factor Investigation - Hyperparameter Search

These are experimental codes:      
- Briefing the data
- Tuning optimal hyperparameter
- Visualize the performance of Models
- Visualize the importance
- Visualize and summerize impacts

In [1]:
%pwd

'/mnt/d/OneDrive/MLD01_Article/MLD01e_Code'

In [2]:
%cd ..

/mnt/d/OneDrive/MLD01_Article

/home/linux/anaconda3/envs/tf/lib/python3.9/site-packages/IPython/core/magics/osm.py:417: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

## Import PAckage

In [3]:
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold, RandomizedSearchCV
from sklearn.metrics import roc_auc_score, classification_report
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

from xgboost import XGBClassifier

## Append Data

In [4]:
df_2016 = pd.read_parquet('Data/01_Napel2016.parquet')
df_2016['Year'] = 2016
df_2022 = pd.read_parquet('Data/01_Napel2022.parquet')
df_2022['Year'] = 2022

In [5]:
df_all = pd.concat([df_2016, df_2022], axis = 0)

In [6]:
df_all.shape

(11568, 352)

In [7]:
df_all = df_all.dropna(axis=1, how="any")

In [8]:
df_all.shape

(11568, 277)

In [9]:
df_all = df_all.set_index(['PSU', 'HHLD'])

In [10]:
df_all.columns

Index(['EcoBelt', 'Prov', 'Rural_Dummy', 'Respon_Female', 'Respon_Age',
       'LivingYear', 'Edu_UnderSLC', 'Edu_Certificate', 'Edu_Bachelor',
       'Edu_Master',
       ...
       'SoilWaterConservationPast25', 'VisitClimateOfficePast25',
       'FoodConsumptionHabitPast25', 'OfffarmActiPast25',
       'NonFarmEmployPast25', 'FamilyMigrationPast25', 'RiskReductionPast25',
       'RoadImprovementPast25', 'CommunityPartipationPast25', 'Year'],
      dtype='object', length=275)

In [11]:
df_all["EcoBelt"] = df_all["EcoBelt"].str.replace('Tarai', 'Terai')

In [12]:
eco_dummies = pd.get_dummies(df_all["EcoBelt"], prefix="EcoBelt").astype(int)
df_all = pd.concat([df_all, eco_dummies], axis=1)

In [13]:
prov_dummies = pd.get_dummies(df_all["Prov"], prefix="Prov").astype(int)
df_all = pd.concat([df_all, prov_dummies], axis=1)

In [14]:
df_all

             EcoBelt          Prov  Rural_Dummy  Respon_Female  Respon_Age  \
PSU   HHLD
101.0 1.0   Mountain         Koshi            1            1.0        49.0
      2.0   Mountain         Koshi            1            0.0        55.0
      3.0   Mountain         Koshi            1            1.0        46.0
      4.0   Mountain         Koshi            1            0.0        78.0
      5.0   Mountain         Koshi            1            0.0        70.0
...              ...           ...          ...            ...         ...
826.0 16.0     Terai  Sudurpaschim            0            0.0        47.0
      17.0     Terai  Sudurpaschim            0            0.0        60.0
      18.0     Terai  Sudurpaschim            0            1.0        47.0
      19.0     Terai  Sudurpaschim            0            0.0        55.0
      20.0     Terai  Sudurpaschim            0            0.0        45.0

            LivingYear  Edu_UnderSLC  Edu_Certificate  Edu_Bachelor  \
PSU   HHLD
101.0 1.0         49.0             0                0             0
      2.0         55.0             1                0             0
      3.0         25.0             0                0             0
      4.0         78.0             0                0             0
      5.0         70.0             1                0             0
...                ...           ...              ...           ...
826.0 16.0        40.0             1                0             0
      17.0        35.0             0                0             0
      18.0        32.0             1                0             0
      19.0        55.0             0                0             0
      20.0        25.0             1                0             0

            Edu_Master  ...  EcoBelt_Hill  EcoBelt_Mountain  EcoBelt_Terai  \
PSU   HHLD              ...
101.0 1.0            0  ...             0                 1              0
      2.0            0  ...             0                 1              0
      3.0            0  ...             0                 1              0
      4.0            0  ...             0                 1              0
      5.0            0  ...             0                 1              0
...                ...  ...           ...               ...            ...
826.0 16.0           0  ...             0                 0              1
      17.0           0  ...             0                 0              1
      18.0           0  ...             0                 0              1
      19.0           0  ...             0                 0              1
      20.0           0  ...             0                 0              1

            Prov_Bagmati  Prov_Gandaki  Prov_Karnali  Prov_Koshi  \
PSU   HHLD
101.0 1.0              0             0             0           1
      2.0              0             0             0           1
      3.0              0             0             0           1
      4.0              0             0             0           1
      5.0              0             0             0           1
...                  ...           ...           ...         ...
826.0 16.0             0             0             0           0
      17.0             0             0             0           0
      18.0             0             0             0           0
      19.0             0             0             0           0
      20.0             0             0             0           0

            Prov_Lumbini  Prov_Madhesh  Prov_Sudurpaschim
PSU   HHLD
101.0 1.0              0             0                  0
      2.0              0             0                  0
      3.0              0             0                  0
      4.0              0             0                  0
      5.0              0             0                  0
...                  ...           ...                ...
826.0 16.0             0             0                  1
      17.0             0             0                  1
      18.0             0             0                  1
      19.0             0             0                  1
      20.0             0             0                  1

[11568 rows x 285 columns]

### Revise Income Resources

In [15]:
df_all['IncomeResAgri_dummy'] = (df_all[['IncomeS1', 'IncomeS2', 'IncomeS3']] == 1).any(axis=1).astype(int)
df_all['IncomeResWage_dummy'] = (df_all[['IncomeS1', 'IncomeS2', 'IncomeS3']] == 2).any(axis=1).astype(int)
df_all['IncomeResNonAgriBusi_dummy'] = (df_all[['IncomeS1', 'IncomeS2', 'IncomeS3']] == 3).any(axis=1).astype(int)
df_all['IncomeResRemit_dummy'] = (df_all[['IncomeS1', 'IncomeS2', 'IncomeS3']] == 4).any(axis=1).astype(int)
df_all['IncomeResOthers_dummy'] = (df_all[['IncomeS1', 'IncomeS2', 'IncomeS3']] == 5).any(axis=1).astype(int)

In [16]:
df_all['ResidenceOwn_dummy'] = (df_all['Own_Resid'] == 1).astype(int)
df_all['ResidenceRent_dummy'] = (df_all['Own_Resid'] == 2).astype(int)
df_all['ResidenceInstitu_dummy'] = (df_all['Own_Resid'] == 3).astype(int)
df_all['ResidenceOthers_dummy'] = (df_all['Own_Resid'] == 4).astype(int)

In [17]:
df_all['ResidInfraPerman_dummy'] = (df_all['Resid_Type'] == 1).astype(int)
df_all['ResidInfraSemi_dummy'] = (df_all['Resid_Type'] == 2).astype(int)
df_all['ResidInfraKachchi_dummy'] = (df_all['Resid_Type'] == 3).astype(int)
df_all['ResidInfraOthers_dummy'] = (df_all['Resid_Type'] == 4).astype(int)

## Checking "HeardClimate_Dummy"

### Dataset building

In [18]:
for here in range(0, df_all.shape[1], 40):
    print(df_all.columns[0+here:40+here])

Index(['EcoBelt', 'Prov', 'Rural_Dummy', 'Respon_Female', 'Respon_Age',
       'LivingYear', 'Edu_UnderSLC', 'Edu_Certificate', 'Edu_Bachelor',
       'Edu_Master', 'Edu_PhD', 'Edu_Literal', 'Edu_Illiterate', 'Edu_year',
       'Female_Ratio', 'U18_Ratio', 'A65_Ratio', 'Edu12_Ratio',
       'Literal_Ratio', 'Household_memberNum', 'Own_Resid', 'Resid_Type',
       'WaterS1', 'WaterS2', 'WaterS3', 'CookFuelS1', 'CookFuelS2',
       'CookFuelS3', 'LightEnergy', 'Toilet', 'IncomeS1', 'IncomeS2',
       'IncomeS3', 'Remittance_dummy', 'Have_AgriLand', 'Radio_dummy',
       'TV_dummy', 'PC_dummy', 'Net_dummy', 'Phone_dummy'],
      dtype='object')
Index(['Mobile_dummy', 'Motorbike_dummy', 'Car_dummy', 'Bike_dummy',
       'OtherVehi_dummy', 'Refrige_dummy', 'HouseHead_AgriExpYear',
       'SavingMembership', 'RegularSaving', 'OrgMembership', 'AgriSupport',
       'Dist_Road', 'Dist_HealthCenter', 'Dist_SecondarySchool', 'Dist_Market',
       'Dist_AgriSupport', 'FramMechan', 'CropIncome', 'LivestockIncome',
       'NonAgriIncome', 'BusiIncome', 'TotalIncome', 'HeardClimate_Dummy',
       'ClimateChanged_Dummy', 'ClimateInfo_Radio', 'ClimateInfo_Telev',
       'ClimateInfo_News ', 'ClimateInfo_Aware', 'ClimateInfo_Local',
       'ClimateInfo_Neigh', 'ClimateInfo_Famil', 'ClimateInfo_Other',
       'ClimateReasonA_Defor', 'ClimateReasonA_Natur', 'ClimateReasonA_Indus',
       'ClimateReasonA_Urban', 'ClimateReasonA_Human', 'ClimateReasonA_Godxs',
       'ClimateReasonA_Earth', 'ClimateReasonA_Other'],
      dtype='object')
Index(['ClimateReasonA_Donxt', 'ClimateReasonB_Defor', 'ClimateReasonB_Natur',
       'ClimateReasonB_Indus', 'ClimateReasonB_Urban', 'ClimateReasonB_Human',
       'ClimateReasonB_Godxs', 'ClimateReasonB_Earth', 'ClimateReasonB_Other',
       'ClimateReasonC_Defor', 'ClimateReasonC_Natur', 'ClimateReasonC_Indus',
       'ClimateReasonC_Urban', 'ClimateReasonC_Human', 'ClimateReasonC_Godxs',
       'ClimateReasonC_Earth', 'ClimateReasonC_Other', 'ExpDummyDR',
       'ExpDummyFF', 'ExpDummyFS', 'ExpDummyFL', 'ExpDummyIN', 'ExpDummyWS',
       'ExpDummyTS', 'ExpDummyHS', 'ExpDummyHR', 'ExpDummySR', 'ExpDummySE',
       'ExpDummyLS', 'ExpDummySS', 'ExpDummyAV', 'ExpDummyGLOF', 'ExpDummyHW',
       'ExpDummyCW', 'ExpDummyDI', 'ExpDummyOT', 'ImpactDR', 'ImpactFF',
       'ImpactFS', 'ImpactFL'],
      dtype='object')
Index(['ImpactIN', 'ImpactWS', 'ImpactTS', 'ImpactHS', 'ImpactHR', 'ImpactSR',
       'ImpactSE', 'ImpactLS', 'ImpactSS', 'ImpactAV', 'ImpactGLOF',
       'ImpactHW', 'ImpactCW', 'ImpactDI', 'ImpactOT',
       'DisasterFoodShortage_DummyDR', 'DisasterFoodShortage_DummyFF',
       'DisasterFoodShortage_DummyFS', 'DisasterFoodShortage_DummyFL',
       'DisasterFoodShortage_DummyIN', 'DisasterFoodShortage_DummyWS',
       'DisasterFoodShortage_DummyTS', 'DisasterFoodShortage_DummyHS',
       'DisasterFoodShortage_DummyHR', 'DisasterFoodShortage_DummySR',
       'DisasterFoodShortage_DummySE', 'DisasterFoodShortage_DummyLS',
       'DisasterFoodShortage_DummySS', 'DisasterFoodShortage_DummyAV',
       'DisasterFoodShortage_DummyGLOF', 'DisasterFoodShortage_DummyHW',
       'DisasterFoodShortage_DummyCW', 'DisasterFoodShortage_DummyDI',
       'DisasterFoodShortage_DummyOT', 'DisasterDie_DummyDR',
       'DisasterDie_DummyFF', 'DisasterDie_DummyFS', 'DisasterDie_DummyFL',
       'DisasterDie_DummyIN', 'DisasterDie_DummyWS'],
      dtype='object')
Index(['DisasterDie_DummyTS', 'DisasterDie_DummyHS', 'DisasterDie_DummyHR',
       'DisasterDie_DummySR', 'DisasterDie_DummySE', 'DisasterDie_DummyLS',
       'DisasterDie_DummySS', 'DisasterDie_DummyAV', 'DisasterDie_DummyGLOF',
       'DisasterDie_DummyHW', 'DisasterDie_DummyCW', 'DisasterDie_DummyDI',
       'DisasterDie_DummyOT', 'DisasterMoneyLoss_DummyDR',
       'DisasterMoneyLoss_DummyFF', 'DisasterMoneyLoss_DummyFS',
       'DisasterMoneyLoss_DummyFL', 'DisasterMoneyLoss_DummyIN',
       'DisasterMoneyLoss_DummyWS', 'DisasterMoneyLoss_DummyTS',
       'DisasterMoneyLoss_DummyHS', 'DisasterMoneyLoss_DummyHR',
       'DisasterMoneyLoss_DummySR', 'DisasterMoneyLoss_DummySE',
       'DisasterMoneyLoss_DummyLS', 'DisasterMoneyLoss_DummySS',
       'DisasterMoneyLoss_DummyAV', 'DisasterMoneyLoss_DummyGLOF',
       'DisasterMoneyLoss_DummyHW', 'DisasterMoneyLoss_DummyCW',
       'DisasterMoneyLoss_DummyDI', 'DisasterMoneyLoss_DummyOT',
       'DisasterMoneyLoss_TotalNRsDR', 'DisasterMoneyLoss_TotalNRsFF',
       'DisasterMoneyLoss_TotalNRsFS', 'DisasterMoneyLoss_TotalNRsFL',
       'DisasterMoneyLoss_TotalNRsIN', 'DisasterMoneyLoss_TotalNRsWS',
       'DisasterMoneyLoss_TotalNRsTS', 'DisasterMoneyLoss_TotalNRsHS'],
      dtype='object')
Index(['DisasterMoneyLoss_TotalNRsHR', 'DisasterMoneyLoss_TotalNRsSR',
       'DisasterMoneyLoss_TotalNRsSE', 'DisasterMoneyLoss_TotalNRsLS',
       'DisasterMoneyLoss_TotalNRsSS', 'DisasterMoneyLoss_TotalNRsAV',
       'DisasterMoneyLoss_TotalNRsGLOF', 'DisasterMoneyLoss_TotalNRsHW',
       'DisasterMoneyLoss_TotalNRsCW', 'DisasterMoneyLoss_TotalNRsDI',
       'DisasterMoneyLoss_TotalNRsOT', 'NewDiseaseCropPast25_Dummy',
       'NewInsectCropPast25_Dummy', 'NewDiseaseLivestockPast25_Dummy',
       'HumanDiseaseIncreasePast25_Dummy', 'HumanVetorDisIncreasePast25_Dummy',
       'HumanWaterDisIncreasePast25_Dummy', 'WaterSourceRiver_IncreaseDummy',
       'WaterSourceRiver_DecreaseDummy', 'WaterSourceRiver_DriedDummy',
       'WaterSourceSpout_IncreaseDummy', 'WaterSourceSpout_DecreaseDummy',
       'WaterSourcePipe_IncreaseDummy', 'WaterSourcePipe_DecreaseDummy',
       'Tree_Drop_Dummy', 'Shrub_Drop_Dummy', 'Herbal_Drop_Dummy',
       'Grass_Drop_Dummy', 'AquAnimal_Drop_Dummy', 'WildAnimal_Drop_Dummy',
       'Birds_Drop_Dummy', 'Insects_Drop_Dummy', 'Shrub_Invasion_Dummy',
       'Climber_Invasion_Dummy', 'Creeper_Invasion_Dummy', 'EarlyTree_Dummy',
       'LaterTree_Dummy', 'EarlyShrub_Dummy', 'LaterShrub_Dummy',
       'EarlyFruit_Dummy'],
      dtype='object')
Index(['LaterFruit_Dummy', 'EarlyHerb_Dummy', 'LaterHerb_Dummy',
       'SkillTrainingPast25', 'ChangeCropPatternPast25', 'LeftLandFallow',
       'RearedLivestockPAst25', 'SuppIrrigationPast25',
       'InvestIrrigationPast25', 'ImprovedSeedPast25',
       'ChangePlantingDatePast25', 'IncreaseInorganicFertilizersPAst25',
       'IncreaseOrganicFertilizersPAst25', 'NewCropsPast25',
       'NewLivestockPast25', 'InvestLivestockPestPast25',
       'InsuranceLivestockPast25', 'InsuranceCropPast25',
       'FarmingLivestockPast25', 'FarmingCropPast25',
       'FarmingLivestockAndCropPast25', 'AgroForestPast25',
       'CompatibleCropPast25', 'TunnelFramingPast25', 'ColdStoragePast25',
       'SoilWaterConservationPast25', 'VisitClimateOfficePast25',
       'FoodConsumptionHabitPast25', 'OfffarmActiPast25',
       'NonFarmEmployPast25', 'FamilyMigrationPast25', 'RiskReductionPast25',
       'RoadImprovementPast25', 'CommunityPartipationPast25', 'Year',
       'EcoBelt_Hill', 'EcoBelt_Mountain', 'EcoBelt_Terai', 'Prov_Bagmati',
       'Prov_Gandaki'],
      dtype='object')
Index(['Prov_Karnali', 'Prov_Koshi', 'Prov_Lumbini', 'Prov_Madhesh',
       'Prov_Sudurpaschim', 'IncomeResAgri_dummy', 'IncomeResWage_dummy',
       'IncomeResNonAgriBusi_dummy', 'IncomeResRemit_dummy',
       'IncomeResOthers_dummy', 'ResidenceOwn_dummy', 'ResidenceRent_dummy',
       'ResidenceInstitu_dummy', 'ResidenceOthers_dummy',
       'ResidInfraPerman_dummy', 'ResidInfraSemi_dummy',
       'ResidInfraKachchi_dummy', 'ResidInfraOthers_dummy'],
      dtype='object')

In [19]:
df_inuse = df_all[['HeardClimate_Dummy', 
                   'Respon_Female', 'Respon_Age', 'LivingYear',  'Edu_Literal', 'Edu_Illiterate', 'Edu_year', # S01
                   'Female_Ratio', 'U18_Ratio', 'A65_Ratio', 'Edu12_Ratio', 'Literal_Ratio', # S02-1
                   'EcoBelt_Hill', 'EcoBelt_Mountain', 'EcoBelt_Terai', 
                   'Prov_Bagmati', 'Prov_Koshi', 'Prov_Lumbini', 'Prov_Madhesh', 'Prov_Sudurpaschim',
                   'Prov_Gandaki', 'Prov_Karnali', # location     
                   'ResidenceOwn_dummy', 'ResidenceRent_dummy', 'ResidenceInstitu_dummy', 'ResidenceOthers_dummy',
                   'ResidInfraPerman_dummy', 'ResidInfraSemi_dummy', 'ResidInfraKachchi_dummy', 'ResidInfraOthers_dummy', # house
                    'Remittance_dummy', 
                   'Have_AgriLand', 'HouseHead_AgriExpYear',
                   'Radio_dummy', 'TV_dummy', 'PC_dummy', 'Net_dummy', 'Phone_dummy',
                   'Mobile_dummy', 'Motorbike_dummy', 'Car_dummy', 'Bike_dummy', 'OtherVehi_dummy', 'Refrige_dummy',
                   'SavingMembership', 'RegularSaving', 'OrgMembership', 'AgriSupport', 
                   'Dist_Road', 'Dist_HealthCenter', 'Dist_SecondarySchool', 'Dist_Market', 'Dist_AgriSupport', 
                   'FramMechan',
                    'IncomeResAgri_dummy', 'IncomeResWage_dummy', 'IncomeResNonAgriBusi_dummy', 'IncomeResRemit_dummy',
                   'IncomeResOthers_dummy', 
                   'CropIncome', 'LivestockIncome', 'NonAgriIncome', 'BusiIncome', 'TotalIncome',
                   'Year'
                   
                  ]]

In [20]:
variname_readable = {'HeardClimate_Dummy':'Heard about Climate Change Dummy', 'Respon_Female':'Female Dummy', 
                     'Respon_Age':'Age', 'LivingYear':'Years Living in Community', 'Edu_UnderSLC':'Education under Secondary Certificate Dummy', 
                     'Edu_Certificate':'Education with Secondary Certificate Dummy', 'Edu_Bachelor':'Education with Bachelor Dummy', 
                     'Edu_Master':'Education with Master Dummy',  'Edu_PhD':'Education with PhD Dummy', 
                     'Edu_Literal':'Literate Education Dummy',  'Edu_Illiterate':'Illiterate Dummy', 'Edu_year':'Education Year',
                     'Female_Ratio':'Female Ratio in Household', 'U18_Ratio':'Member Under 18 Ratio', 'A65_Ratio':'Seniors Ratio',
                     'Edu12_Ratio':"Member with 12-Year Education or above Ratio", "Literal_Ratio": "Literate Member Ratio",
                     'EcoBelt_Hill': "EcoBelt Hill Dummy", 'EcoBelt_Mountain': "EcoBelt Mountain Dummy", 'EcoBelt_Terai': "EcoBelt Terai Dummy",
                     'Prov_Bagmati': "Province Bagmati Dummy", 'Prov_Koshi': "Province Koshi Dummy", 'Prov_Lumbini': "Province Lumbibi Dummy",
                     'Prov_Madhesh': "Province Madhesh Dummy", 'Prov_Sudurpaschim': "Province Sudurpaschim Dummy", 'Prov_Gandaki': "Province Gandaki Dummy",
                     'Prov_Karnali': "Province Karnali Dummy",
                     'ResidenceOwn_dummy': "Owned Residence Ownership Dummy", 'ResidenceRent_dummy': 'Rented Residence Ownership Dummy', 
                     'ResidenceInstitu_dummy': 'Institutional Residence Ownership Dummy', 'ResidenceOthers_dummy': 'Other-type Residence Ownership Dummy',
                     'ResidInfraPerman_dummy': 'Permanent Residence Dummy', 'ResidInfraSemi_dummy': 'Semi-Permanent Residence Dummy', 
                     'ResidInfraKachchi_dummy': "Kachchi Residence Dummy", 'ResidInfraOthers_dummy': 'Other Residence Infrastructure Dummy', # house
                     'Remittance_dummy' : "Have Remittance",
                     'Have_AgriLand': "Having Agricultural Land Dummy", 'HouseHead_AgriExpYear': "Household Head Agricultural Experience",
                     'Radio_dummy': "Having Radio Dummy", 'TV_dummy': "Having TV Dummy", 'PC_dummy': "Having Computer Dummy", 'Net_dummy': "Having Internet Dummy",
                     'Phone_dummy': "Having Telephone Dummy", 'Mobile_dummy': "Having Mobile Dummy", 'Motorbike_dummy': "Having Motorbike Dummy", 
                     'Car_dummy': "Having Car Dummy", 'Bike_dummy': "Having Bike Dummy", 'OtherVehi_dummy': "Having Other Vehicle Dummy", 
                     'Refrige_dummy':"Having Refrigator Dummy",
                     'SavingMembership': "Saving Membership Dummy", 'RegularSaving': 'Having Regular Saving Dummy', 
                     'OrgMembership': 'Having Organization Membership Dummy', 'AgriSupport':'Agricultural Supporting Dummy', 
                     'Dist_Road': 'Distance to Motorable Road', 'Dist_HealthCenter': "Distance to Health Center", 
                     'Dist_SecondarySchool': "Distance to Secondary School", 'Dist_Market':"Distance to Market", 'Dist_AgriSupport': 'Distance to Agricultural Center', 
                     'FramMechan':'Farm Mechanization Dummy',
                     'IncomeResAgri_dummy': "Agricultural Income Source Dummy", 'IncomeResWage_dummy': "Wage Income Source Dummy",
                     'IncomeResNonAgriBusi_dummy': "Non-Agricultural Business Income Source Dummy", 'IncomeResRemit_dummy': "Remittance Income Dummy",
                     'IncomeResOthers_dummy': "Others Income Source Dummy", 
                     'CropIncome': "Crop Income", 'LivestockIncome': "Livestock Income", 'NonAgriIncome': "Non-agricultural Income", 
                     'BusiIncome': "Business Income", 'TotalIncome': "Total Income",
                     'Year': "Survey Year"                    
                    }

In [21]:
data_summary = df_inuse.describe().T

In [22]:
data_summary.index = data_summary.index.map(variname_readable)

In [23]:
data_summary.to_excel("MLD01e_Results/Table01_DataSummary_v1.xlsx")

In [24]:
df_inuse.columns = df_inuse.columns.map(variname_readable)

In [25]:
data_summary

,count,mean,std,min,25%,50%,75%,max
Heard about Climate Change Dummy,11568.0,0.421508,4.938219e-01,0.0,0.0,0.0,1.0,1.0
Female Dummy,11568.0,0.285183,4.515212e-01,0.0,0.0,0.0,1.0,1.0
Age,11568.0,58.681189,1.027651e+01,45.0,50.0,58.0,66.0,95.0
Years Living in Community,11568.0,50.082382,1.582942e+01,25.0,40.0,50.0,60.0,730.0
Literate Education Dummy,11568.0,0.169001,3.747687e-01,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...
Livestock Income,11568.0,15559.887275,9.565885e+04,0.0,0.0,0.0,15000.0,7200000.0
Non-agricultural Income,11568.0,79973.158368,2.710275e+05,0.0,0.0,0.0,50000.0,10000000.0
Business Income,11568.0,202175.389004,1.112664e+06,0.0,0.0,15000.0,240000.0,99000000.0
Total Income,11568.0,323942.349066,1.143592e+06,0.0,54000.0,170000.0,400000.0,99200000.0
Survey Year,11568.0,2019.375519,2.976533e+00,2016.0,2016.0,2022.0,2022.0,2022.0

## Hyper Tunining

In [26]:
y = df_inuse['Heard about Climate Change Dummy'].astype(int)
X = df_inuse.drop(columns=['Heard about Climate Change Dummy'])

pos = y.sum()
neg = len(y) - pos
scale_pos_weight = (neg / pos) if pos > 0 else 1.0

In [27]:
clf = XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    tree_method="hist",
    random_state=42,
    scale_pos_weight=scale_pos_weight,
    device = 'cuda'
)

In [28]:
param_distributions = {
    'n_estimators': [200, 500, 1_000, 2_000],
    'max_depth': [4,  8, 16],
    'learning_rate': [0.01, 0.05, 0.1],
    'subsample': [0.7, 0.8, 0.9, 1.0],
    'colsample_bytree': [0.7, 0.8, 0.9, 1.0],
    'min_child_weight': [1, 2, 5, 10]
}

In [29]:
cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

search = RandomizedSearchCV(
    estimator=clf,
    param_distributions=param_distributions,
    n_iter=200,                 # increase for a more exhaustive search if you have time
    scoring='accuracy',
    return_train_score=True,
    cv=cv,
    verbose=3,
    refit=True,                # refit on entire data with best params
    random_state=42
)

search.fit(X, y)

Fitting 10 folds for each of 200 candidates, totalling 2000 fits

/home/linux/anaconda3/envs/tf/lib/python3.9/site-packages/xgboost/core.py:160: UserWarning: [18:01:28] WARNING: /workspace/src/common/error_msg.cc:58: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  warnings.warn(smsg, UserWarning)

[CV 1/10] END colsample_bytree=0.9, learning_rate=0.1, max_depth=8, min_child_weight=5, n_estimators=1000, subsample=0.7;, score=(train=1.000, test=0.711) total time=   5.9s
[CV 2/10] END colsample_bytree=0.9, learning_rate=0.1, max_depth=8, min_child_weight=5, n_estimators=1000, subsample=0.7;, score=(train=1.000, test=0.738) total time=   4.5s
[CV 3/10] END colsample_bytree=0.9, learning_rate=0.1, max_depth=8, min_child_weight=5, n_estimators=1000, subsample=0.7;, score=(train=1.000, test=0.737) total time=   4.4s
[CV 4/10] END colsample_bytree=0.9, learning_rate=0.1, max_depth=8, min_child_weight=5, n_estimators=1000, subsample=0.7;, score=(train=1.000, test=0.735) total time=   4.6s
[CV 5/10] END colsample_bytree=0.9, learning_rate=0.1, max_depth=8, min_child_weight=5, n_estimators=1000, subsample=0.7;, score=(train=1.000, test=0.749) total time=   4.6s
[CV 6/10] END colsample_bytree=0.9, learning_rate=0.1, max_depth=8, min_child_weight=5, n_estimators=1000, subsample=0.7;, score=(train=1.000, test=0.748) total time=   4.5s
[CV 7/10] END colsample_bytree=0.9, learning_rate=0.1, max_depth=8, min_child_weight=5, n_estimators=1000, subsample=0.7;, score=(train=1.000, test=0.760) total time=   4.4s
[CV 8/10] END colsample_bytree=0.9, learning_rate=0.1, max_depth=8, min_child_weight=5, n_estimators=1000, subsample=0.7;, score=(train=1.000, test=0.748) total time=   4.6s
[CV 9/10] END colsample_bytree=0.9, learning_rate=0.1, max_depth=8, min_child_weight=5, n_estimators=1000, subsample=0.7;, score=(train=1.000, test=0.740) total time=   4.6s
[CV 10/10] END colsample_bytree=0.9, learning_rate=0.1, max_depth=8, min_child_weight=5, n_estimators=1000, subsample=0.7;, score=(train=1.000, test=0.733) total time=   4.6s
[CV 1/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=8, min_child_weight=10, n_estimators=2000, subsample=0.7;, score=(train=1.000, test=0.717) total time=   9.0s
[CV 2/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=8, min_child_weight=10, n_estimators=2000, subsample=0.7;, score=(train=1.000, test=0.740) total time=   9.2s
[CV 3/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=8, min_child_weight=10, n_estimators=2000, subsample=0.7;, score=(train=1.000, test=0.738) total time=   9.2s
[CV 4/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=8, min_child_weight=10, n_estimators=2000, subsample=0.7;, score=(train=1.000, test=0.736) total time=   9.2s
[CV 5/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=8, min_child_weight=10, n_estimators=2000, subsample=0.7;, score=(train=1.000, test=0.748) total time=   9.5s
[CV 6/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=8, min_child_weight=10, n_estimators=2000, subsample=0.7;, score=(train=1.000, test=0.735) total time=   9.4s
[CV 7/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=8, min_child_weight=10, n_estimators=2000, subsample=0.7;, score=(train=1.000, test=0.748) total time=   8.9s
[CV 8/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=8, min_child_weight=10, n_estimators=2000, subsample=0.7;, score=(train=1.000, test=0.753) total time=   9.1s
[CV 9/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=8, min_child_weight=10, n_estimators=2000, subsample=0.7;, score=(train=1.000, test=0.766) total time=   8.8s
[CV 10/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=8, min_child_weight=10, n_estimators=2000, subsample=0.7;, score=(train=1.000, test=0.730) total time=   9.6s
[CV 1/10] END colsample_bytree=0.9, learning_rate=0.05, max_depth=8, min_child_weight=1, n_estimators=2000, subsample=0.9;, score=(train=1.000, test=0.724) total time=  10.3s
[CV 2/10] END colsample_bytree=0.9, learning_rate=0.05, max_depth=8, min_child_weight=1, n_estimators=2000, subsample=0.9;, score=(train=1.000, test=0.750) total time=  10.1s
[CV 3/10] END colsample_bytree=0.9, learning_rate=0.05, max_depth=8, min_child_weight=1, n_estimators=2000, subsample=0.9;, score=(train=1.000, test=0.760) total time=  10.2s
[CV 4/10] END colsample_bytree=0.9, learning_rate=0.05, max_depth=8, min_child_weight=1, n_estimators=2000, subsample=0.9;, score=(train=1.000, test=0.754) total time=  10.3s
[CV 5/10] END colsample_bytree=0.9, learning_rate=0.05, max_depth=8, min_child_weight=1, n_estimators=2000, subsample=0.9;, score=(train=1.000, test=0.758) total time=  10.0s
[CV 6/10] END colsample_bytree=0.9, learning_rate=0.05, max_depth=8, min_child_weight=1, n_estimators=2000, subsample=0.9;, score=(train=1.000, test=0.745) total time=   9.8s
[CV 7/10] END colsample_bytree=0.9, learning_rate=0.05, max_depth=8, min_child_weight=1, n_estimators=2000, subsample=0.9;, score=(train=1.000, test=0.757) total time=   9.8s
[CV 8/10] END colsample_bytree=0.9, learning_rate=0.05, max_depth=8, min_child_weight=1, n_estimators=2000, subsample=0.9;, score=(train=1.000, test=0.755) total time=  10.4s
[CV 9/10] END colsample_bytree=0.9, learning_rate=0.05, max_depth=8, min_child_weight=1, n_estimators=2000, subsample=0.9;, score=(train=1.000, test=0.750) total time=  10.4s
[CV 10/10] END colsample_bytree=0.9, learning_rate=0.05, max_depth=8, min_child_weight=1, n_estimators=2000, subsample=0.9;, score=(train=1.000, test=0.739) total time=  10.4s
[CV 1/10] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=2000, subsample=0.7;, score=(train=0.824, test=0.743) total time=   5.8s
[CV 2/10] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=2000, subsample=0.7;, score=(train=0.823, test=0.754) total time=   6.3s
[CV 3/10] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=2000, subsample=0.7;, score=(train=0.819, test=0.758) total time=   6.5s
[CV 4/10] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=2000, subsample=0.7;, score=(train=0.819, test=0.748) total time=   6.4s
[CV 5/10] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=2000, subsample=0.7;, score=(train=0.819, test=0.766) total time=   6.3s
[CV 6/10] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=2000, subsample=0.7;, score=(train=0.822, test=0.758) total time=   6.5s
[CV 7/10] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=2000, subsample=0.7;, score=(train=0.821, test=0.769) total time=   6.1s
[CV 8/10] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=2000, subsample=0.7;, score=(train=0.820, test=0.751) total time=   6.5s
[CV 9/10] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=2000, subsample=0.7;, score=(train=0.818, test=0.762) total time=   6.5s
[CV 10/10] END colsample_bytree=0.7, learning_rate=0.01, max_depth=4, min_child_weight=5, n_estimators=2000, subsample=0.7;, score=(train=0.821, test=0.738) total time=   6.5s
[CV 1/10] END colsample_bytree=0.9, learning_rate=0.05, max_depth=4, min_child_weight=10, n_estimators=500, subsample=0.9;, score=(train=0.831, test=0.738) total time=   1.6s
[CV 2/10] END colsample_bytree=0.9, learning_rate=0.05, max_depth=4, min_child_weight=10, n_estimators=500, subsample=0.9;, score=(train=0.833, test=0.756) total time=   1.6s
[CV 3/10] END colsample_bytree=0.9, learning_rate=0.05, max_depth=4, min_child_weight=10, n_estimators=500, subsample=0.9;, score=(train=0.828, test=0.755) total time=   1.6s
[CV 4/10] END colsample_bytree=0.9, learning_rate=0.05, max_depth=4, min_child_weight=10, n_estimators=500, subsample=0.9;, score=(train=0.829, test=0.746) total time=   1.6s
[CV 5/10] END colsample_bytree=0.9, learning_rate=0.05, max_depth=4, min_child_weight=10, n_estimators=500, subsample=0.9;, score=(train=0.835, test=0.768) total time=   1.7s
[CV 6/10] END colsample_bytree=0.9, learning_rate=0.05, max_depth=4, min_child_weight=10, n_estimators=500, subsample=0.9;, score=(train=0.833, test=0.755) total time=   1.7s
[CV 7/10] END colsample_bytree=0.9, learning_rate=0.05, max_depth=4, min_child_weight=10, n_estimators=500, subsample=0.9;, score=(train=0.831, test=0.762) total time=   1.7s
[CV 8/10] END colsample_bytree=0.9, learning_rate=0.05, max_depth=4, min_child_weight=10, n_estimators=500, subsample=0.9;, score=(train=0.833, test=0.752) total time=   1.6s
[CV 9/10] END colsample_bytree=0.9, learning_rate=0.05, max_depth=4, min_child_weight=10, n_estimators=500, subsample=0.9;, score=(train=0.830, test=0.765) total time=   1.6s
[CV 10/10] END colsample_bytree=0.9, learning_rate=0.05, max_depth=4, min_child_weight=10, n_estimators=500, subsample=0.9;, score=(train=0.831, test=0.742) total time=   1.7s
[CV 1/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=4, min_child_weight=2, n_estimators=500, subsample=0.9;, score=(train=0.883, test=0.729) total time=   1.6s
[CV 2/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=4, min_child_weight=2, n_estimators=500, subsample=0.9;, score=(train=0.885, test=0.746) total time=   1.6s
[CV 3/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=4, min_child_weight=2, n_estimators=500, subsample=0.9;, score=(train=0.885, test=0.756) total time=   1.7s
[CV 4/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=4, min_child_weight=2, n_estimators=500, subsample=0.9;, score=(train=0.882, test=0.749) total time=   1.6s
[CV 5/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=4, min_child_weight=2, n_estimators=500, subsample=0.9;, score=(train=0.886, test=0.754) total time=   1.7s
[CV 6/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=4, min_child_weight=2, n_estimators=500, subsample=0.9;, score=(train=0.886, test=0.760) total time=   1.6s
[CV 7/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=4, min_child_weight=2, n_estimators=500, subsample=0.9;, score=(train=0.881, test=0.761) total time=   1.6s
[CV 8/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=4, min_child_weight=2, n_estimators=500, subsample=0.9;, score=(train=0.881, test=0.748) total time=   1.6s
[CV 9/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=4, min_child_weight=2, n_estimators=500, subsample=0.9;, score=(train=0.882, test=0.749) total time=   1.6s
[CV 10/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=4, min_child_weight=2, n_estimators=500, subsample=0.9;, score=(train=0.880, test=0.737) total time=   1.6s
[CV 1/10] END colsample_bytree=0.9, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=500, subsample=1.0;, score=(train=0.770, test=0.743) total time=   1.7s
[CV 2/10] END colsample_bytree=0.9, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=500, subsample=1.0;, score=(train=0.769, test=0.745) total time=   1.6s
[CV 3/10] END colsample_bytree=0.9, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=500, subsample=1.0;, score=(train=0.766, test=0.743) total time=   1.6s
[CV 4/10] END colsample_bytree=0.9, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=500, subsample=1.0;, score=(train=0.769, test=0.748) total time=   1.6s
[CV 5/10] END colsample_bytree=0.9, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=500, subsample=1.0;, score=(train=0.768, test=0.745) total time=   1.6s
[CV 6/10] END colsample_bytree=0.9, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=500, subsample=1.0;, score=(train=0.768, test=0.750) total time=   1.7s
[CV 7/10] END colsample_bytree=0.9, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=500, subsample=1.0;, score=(train=0.768, test=0.759) total time=   1.6s
[CV 8/10] END colsample_bytree=0.9, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=500, subsample=1.0;, score=(train=0.769, test=0.734) total time=   1.6s
[CV 9/10] END colsample_bytree=0.9, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=500, subsample=1.0;, score=(train=0.766, test=0.744) total time=   1.5s
[CV 10/10] END colsample_bytree=0.9, learning_rate=0.01, max_depth=4, min_child_weight=1, n_estimators=500, subsample=1.0;, score=(train=0.769, test=0.728) total time=   1.6s
[CV 1/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=4, min_child_weight=10, n_estimators=1000, subsample=0.7;, score=(train=0.924, test=0.719) total time=   3.3s
[CV 2/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=4, min_child_weight=10, n_estimators=1000, subsample=0.7;, score=(train=0.923, test=0.743) total time=   3.3s
[CV 3/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=4, min_child_weight=10, n_estimators=1000, subsample=0.7;, score=(train=0.923, test=0.742) total time=   3.2s
[CV 4/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=4, min_child_weight=10, n_estimators=1000, subsample=0.7;, score=(train=0.922, test=0.746) total time=   3.3s
[CV 5/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=4, min_child_weight=10, n_estimators=1000, subsample=0.7;, score=(train=0.922, test=0.754) total time=   3.3s
[CV 6/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=4, min_child_weight=10, n_estimators=1000, subsample=0.7;, score=(train=0.926, test=0.758) total time=   3.3s
[CV 7/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=4, min_child_weight=10, n_estimators=1000, subsample=0.7;, score=(train=0.919, test=0.750) total time=   3.3s
[CV 8/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=4, min_child_weight=10, n_estimators=1000, subsample=0.7;, score=(train=0.921, test=0.760) total time=   3.3s
[CV 9/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=4, min_child_weight=10, n_estimators=1000, subsample=0.7;, score=(train=0.924, test=0.755) total time=   3.3s
[CV 10/10] END colsample_bytree=0.7, learning_rate=0.1, max_depth=4, min_child_weight=10, n_estimators=1000, subsample=0.7;, score=(train=0.921, test=0.725) total time=   3.2s
[CV 1/10] END colsample_bytree=1.0, learning_rate=0.05, max_depth=8, min_child_weight=5, n_estimators=200, subsample=0.7;, score=(train=0.928, test=0.734) total time=   1.3s
[CV 2/10] END colsample_bytree=1.0, learning_rate=0.05, max_depth=8, min_child_weight=5, n_estimators=200, subsample=0.7;, score=(train=0.927, test=0.759) total time=   1.1s
[CV 3/10] END colsample_bytree=1.0, learning_rate=0.05, max_depth=8, min_child_weight=5, n_estimators=200, subsample=0.7;, score=(train=0.926, test=0.765) total time=   1.1s
[CV 4/10] END colsample_bytree=1.0, learning_rate=0.05, max_depth=8, min_child_weight=5, n_estimators=200, subsample=0.7;, score=(train=0.927, test=0.762) total time=   1.1s
[CV 5/10] END colsample_bytree=1.0, learning_rate=0.05, max_depth=8, min_child_weight=5, n_estimators=200, subsample=0.7;, score=(train=0.927, test=0.767) total time=   1.0s
[CV 6/10] END colsample_bytree=1.0, learning_rate=0.05, max_depth=8, min_child_weight=5, n_estimators=200, subsample=0.7;, score=(train=0.926, test=0.751) total time=   1.0s
[CV 7/10] END colsample_bytree=1.0, learning_rate=0.05, max_depth=8, min_child_weight=5, n_estimators=200, subsample=0.7;, score=(train=0.928, test=0.760) total time=   1.1s
[CV 8/10] END colsample_bytree=1.0, learning_rate=0.05, max_depth=8, min_child_weight=5, n_estimators=200, subsample=0.7;, score=(train=0.927, test=0.751) total time=   1.0s
[CV 9/10] END colsample_bytree=1.0, learning_rate=0.05, max_depth=8, min_child_weight=5, n_estimators=200, subsample=0.7;, score=(train=0.926, test=0.760) total time=   1.0s
[CV 10/10] END colsample_bytree=1.0, learning_rate=0.05, max_depth=8, min_child_weight=5, n_estimators=200, subsample=0.7;, score=(train=0.930, test=0.737) total time=   1.0s
[CV 1/10] END colsample_bytree=0.9, learning_rate=0.01, max_depth=8, min_child_weight=2, n_estimators=2000, subsample=0.8;, score=(train=0.996, test=0.741) total time=  10.6s
[CV 2/10] END colsample_bytree=0.9, learning_rate=0.01, max_depth=8, min_child_weight=2, n_estimators=2000, subsample=0.8;, score=(train=0.995, test=0.749) total time=  10.7s
[CV 3/10] END colsample_bytree=0.9, learning_rate=0.01, max_depth=8, min_child_weight=2, n_estimators=2000, subsample=0.8;, score=(train=0.994, test=0.764) total time=  10.8s
[CV 4/10] END colsample_bytree=0.9, learning_rate=0.01, max_depth=8, min_child_weight=2, n_estimators=2000, subsample=0.8;, score=(train=0.994, test=0.758) total time=  10.8s
[CV 5/10] END colsample_bytree=0.9, learning_rate=0.01, max_depth=8, min_child_weight=2, n_estimators=2000, subsample=0.8;, score=(train=0.995, test=0.769) total time=  10.7s
[CV 6/10] END colsample_bytree=0.9, learning_rate=0.01, max_depth=8, min_child_weight=2, n_estimators=2000, subsample=0.8;, score=(train=0.995, test=0.769) total time=  10.7s
[CV 7/10] END colsample_bytree=0.9, learning_rate=0.01, max_depth=8, min_child_weight=2, n_estimators=2000, subsample=0.8;, score=(train=0.995, test=0.767) total time=  10.7s
[CV 8/10] END colsample_bytree=0.9, learning_rate=0.01, max_depth=8, min_child_weight=2, n_estimators=2000, subsample=0.8;, score=(train=0.995, test=0.759) total time=  10.3s
[CV 9/10] END colsample_bytree=0.9, learning_rate=0.01, max_depth=8, min_child_weight=2, n_estimators=2000, subsample=0.8;, score=(train=0.994, test=0.759) total time=  10.8s
[CV 10/10] END colsample_bytree=0.9, learning_rate=0.01, max_depth=8, min_child_weight=2, n_estimators=2000, subsample=0.8;, score=(train=0.995, test=0.746) total time=  10.9s
[CV 1/10] END colsample_bytree=0.7, learning_rate=0.05, max_depth=4, min_child_weight=10, n_estimators=2000, subsample=0.9;, score=(train=0.931, test=0.743) total time=   5.4s
[CV 2/10] END colsample_bytree=0.7, learning_rate=0.05, max_depth=4, min_child_weight=10, n_estimators=2000, subsample=0.9;, score=(train=0.928, test=0.755) total time=   6.4s
[CV 3/10] END colsample_bytree=0.7, learning_rate=0.05, max_depth=4, min_child_weight=10, n_estimators=2000, subsample=0.9;, score=(train=0.927, test=0.748) total time=   6.1s
[CV 4/10] END colsample_bytree=0.7, learning_rate=0.05, max_depth=4, min_child_weight=10, n_estimators=2000, subsample=0.9;, score=(train=0.927, test=0.746) total time=   6.2s
[CV 5/10] END colsample_bytree=0.7, learning_rate=0.05, max_depth=4, min_child_weight=10, n_estimators=2000, subsample=0.9;, score=(train=0.927, test=0.755) total time=   6.4s
[CV 6/10] END colsample_bytree=0.7, learning_rate=0.05, max_depth=4, min_child_weight=10, n_estimators=2000, subsample=0.9;, score=(train=0.929, test=0.754) total time=   6.1s
[CV 7/10] END colsample_bytree=0.7, learning_rate=0.05, max_depth=4, min_child_weight=10, n_estimators=2000, subsample=0.9;, score=(train=0.927, test=0.755) total time=   6.4s
[CV 8/10] END colsample_bytree=0.7, learning_rate=0.05, max_depth=4, min_child_weight=10, n_estimators=2000, subsample=0.9;, score=(train=0.929, test=0.754) total time=   6.8s
[CV 9/10] END colsample_bytree=0.7, learning_rate=0.05, max_depth=4, min_child_weight=10, n_estimators=2000, subsample=0.9;, score=(train=0.927, test=0.751) total time=   6.3s
[CV 10/10] END colsample_bytree=0.7, learning_rate=0.05, max_depth=4, min_child_weight=10, n_estimators=2000, subsample=0.9;, score=(train=0.928, test=0.732) total time=   6.0s
[CV 1/10] END colsample_bytree=0.9, learning_rate=0.1, max_depth=16, min_child_weight=2, n_estimators=500, subsample=0.7;, score=(train=1.000, test=0.736) total time=   4.6s
[CV 2/10] END colsample_bytree=0.9, learning_rate=0.1, max_depth=16, min_child_weight=2, n_estimators=500, subsample=0.7;, score=(train=1.000, test=0.746) total time=   4.3s
[CV 3/10] END colsample_bytree=0.9, learning_rate=0.1, max_depth=16, min_child_weight=2, n_estimators=500, subsample=0.7;, score=(train=1.000, test=0.755) total time=   4.4s
[CV 4/10] END colsample_bytree=0.9, learning_rate=0.1, max_depth=16, min_child_weight=2, n_estimators=500, subsample=0.7;, score=(train=1.000, test=0.753) total time=   4.3s

RandomizedSearchCV(cv=StratifiedKFold(n_splits=10, random_state=42, shuffle=True),
                   estimator=XGBClassifier(base_score=None, booster=None,
                                           callbacks=None,
                                           colsample_bylevel=None,
                                           colsample_bynode=None,
                                           colsample_bytree=None, device='cuda',
                                           early_stopping_rounds=None,
                                           enable_categorical=False,
                                           eval_metric='logloss',
                                           feature_types=None, gamma=None,
                                           grow_policy=None,...
                                           n_estimators=None, n_jobs=None,
                                           num_parallel_tree=None,
                                           random_state=42, ...),
                   n_iter=200,
                   param_distributions={'colsample_bytree': [0.7, 0.8, 0.9,
                                                             1.0],
                                        'learning_rate': [0.01, 0.05, 0.1],
                                        'max_depth': [4, 8, 16],
                                        'min_child_weight': [1, 2, 5, 10],
                                        'n_estimators': [200, 500, 1000, 2000],
                                        'subsample': [0.7, 0.8, 0.9, 1.0]},
                   random_state=42, return_train_score=True, scoring='accuracy',
                   verbose=3)

In [30]:
# 7) Results
print("Best mean CV accuracy:", f"{search.best_score_:.4f}")
print("Best params:")
for k, v in search.best_params_.items():
    print(f"  {k}: {v}")

Best mean CV accuracy: 0.7603
Best params:
  subsample: 0.7
  n_estimators: 500
  min_child_weight: 5
  max_depth: 8
  learning_rate: 0.01
  colsample_bytree: 0.7

In [31]:
cvres = pd.DataFrame(search.cv_results_)

In [32]:
cvres.to_parquet('MLD01e_Results/MLD01e_C01_KnowledgeFactorInvestigation.parquet')

In [33]:
cols = ['mean_test_score', 'std_test_score', 'rank_test_score'] + [c for c in cvres.columns if c.startswith('param_')]
cvres_sorted = cvres.sort_values('rank_test_score')[cols].head(10)

In [34]:
cvres_sorted

,mean_test_score,std_test_score,rank_test_score,param_subsample,param_n_estimators,param_min_child_weight,param_max_depth,param_learning_rate,param_colsample_bytree
87,0.760286,0.008304,1,0.7,500,5,8,0.01,0.7
189,0.760027,0.009973,2,0.9,1000,2,8,0.01,1.0
150,0.759508,0.006709,3,1.0,200,1,8,0.05,0.7
59,0.759162,0.009074,4,0.9,500,5,8,0.01,0.8
82,0.759076,0.011507,5,0.7,1000,1,16,0.01,0.9
114,0.758643,0.008779,6,0.9,200,5,8,0.05,0.7
111,0.758556,0.009120,7,0.7,500,5,16,0.01,1.0
79,0.758039,0.010451,8,0.7,1000,5,16,0.01,0.8
9,0.758038,0.009435,9,0.8,2000,2,8,0.01,0.9
77,0.757866,0.009483,10,0.9,500,1,16,0.01,0.7