# Data Summary of Dataset

In [1]:
%pwd

'/mnt/d/OneDrive/MLD01_Article/MLD01e_Code'

In [2]:
%cd ..

/mnt/d/OneDrive/MLD01_Article

/home/linux/anaconda3/envs/tf/lib/python3.9/site-packages/IPython/core/magics/osm.py:417: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

## Import PAckage

In [3]:
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd

## Append Data

In [4]:
df_2016 = pd.read_parquet('Data/01_Napel2016.parquet')
df_2016['Year'] = 2016
df_2022 = pd.read_parquet('Data/01_Napel2022.parquet')
df_2022['Year'] = 2022

In [5]:
df_all = pd.concat([df_2016, df_2022], axis = 0)

In [6]:
df_all.shape

(11568, 352)

In [7]:
df_all = df_all.dropna(axis=1, how="any")

In [8]:
df_all.shape

(11568, 277)

In [9]:
df_all = df_all.set_index(['PSU', 'HHLD'])

In [10]:
df_all.columns

Index(['EcoBelt', 'Prov', 'Rural_Dummy', 'Respon_Female', 'Respon_Age',
       'LivingYear', 'Edu_UnderSLC', 'Edu_Certificate', 'Edu_Bachelor',
       'Edu_Master',
       ...
       'SoilWaterConservationPast25', 'VisitClimateOfficePast25',
       'FoodConsumptionHabitPast25', 'OfffarmActiPast25',
       'NonFarmEmployPast25', 'FamilyMigrationPast25', 'RiskReductionPast25',
       'RoadImprovementPast25', 'CommunityPartipationPast25', 'Year'],
      dtype='object', length=275)

In [11]:
df_all["EcoBelt"] = df_all["EcoBelt"].str.replace('Tarai', 'Terai')

In [12]:
eco_dummies = pd.get_dummies(df_all["EcoBelt"], prefix="EcoBelt").astype(int)
df_all = pd.concat([df_all, eco_dummies], axis=1)

In [13]:
prov_dummies = pd.get_dummies(df_all["Prov"], prefix="Prov").astype(int)
df_all = pd.concat([df_all, prov_dummies], axis=1)

In [14]:
df_all

             EcoBelt          Prov  Rural_Dummy  Respon_Female  Respon_Age  \
PSU   HHLD
101.0 1.0   Mountain         Koshi            1            1.0        49.0
      2.0   Mountain         Koshi            1            0.0        55.0
      3.0   Mountain         Koshi            1            1.0        46.0
      4.0   Mountain         Koshi            1            0.0        78.0
      5.0   Mountain         Koshi            1            0.0        70.0
...              ...           ...          ...            ...         ...
826.0 16.0     Terai  Sudurpaschim            0            0.0        47.0
      17.0     Terai  Sudurpaschim            0            0.0        60.0
      18.0     Terai  Sudurpaschim            0            1.0        47.0
      19.0     Terai  Sudurpaschim            0            0.0        55.0
      20.0     Terai  Sudurpaschim            0            0.0        45.0

            LivingYear  Edu_UnderSLC  Edu_Certificate  Edu_Bachelor  \
PSU   HHLD
101.0 1.0         49.0             0                0             0
      2.0         55.0             1                0             0
      3.0         25.0             0                0             0
      4.0         78.0             0                0             0
      5.0         70.0             1                0             0
...                ...           ...              ...           ...
826.0 16.0        40.0             1                0             0
      17.0        35.0             0                0             0
      18.0        32.0             1                0             0
      19.0        55.0             0                0             0
      20.0        25.0             1                0             0

            Edu_Master  ...  EcoBelt_Hill  EcoBelt_Mountain  EcoBelt_Terai  \
PSU   HHLD              ...
101.0 1.0            0  ...             0                 1              0
      2.0            0  ...             0                 1              0
      3.0            0  ...             0                 1              0
      4.0            0  ...             0                 1              0
      5.0            0  ...             0                 1              0
...                ...  ...           ...               ...            ...
826.0 16.0           0  ...             0                 0              1
      17.0           0  ...             0                 0              1
      18.0           0  ...             0                 0              1
      19.0           0  ...             0                 0              1
      20.0           0  ...             0                 0              1

            Prov_Bagmati  Prov_Gandaki  Prov_Karnali  Prov_Koshi  \
PSU   HHLD
101.0 1.0              0             0             0           1
      2.0              0             0             0           1
      3.0              0             0             0           1
      4.0              0             0             0           1
      5.0              0             0             0           1
...                  ...           ...           ...         ...
826.0 16.0             0             0             0           0
      17.0             0             0             0           0
      18.0             0             0             0           0
      19.0             0             0             0           0
      20.0             0             0             0           0

            Prov_Lumbini  Prov_Madhesh  Prov_Sudurpaschim
PSU   HHLD
101.0 1.0              0             0                  0
      2.0              0             0                  0
      3.0              0             0                  0
      4.0              0             0                  0
      5.0              0             0                  0
...                  ...           ...                ...
826.0 16.0             0             0                  1
      17.0             0             0                  1
      18.0             0             0                  1
      19.0             0             0                  1
      20.0             0             0                  1

[11568 rows x 285 columns]

### Revise Income Resources

In [15]:
df_all['IncomeResAgri_dummy'] = (df_all[['IncomeS1', 'IncomeS2', 'IncomeS3']] == 1).any(axis=1).astype(int)
df_all['IncomeResWage_dummy'] = (df_all[['IncomeS1', 'IncomeS2', 'IncomeS3']] == 2).any(axis=1).astype(int)
df_all['IncomeResNonAgriBusi_dummy'] = (df_all[['IncomeS1', 'IncomeS2', 'IncomeS3']] == 3).any(axis=1).astype(int)
df_all['IncomeResRemit_dummy'] = (df_all[['IncomeS1', 'IncomeS2', 'IncomeS3']] == 4).any(axis=1).astype(int)
df_all['IncomeResOthers_dummy'] = (df_all[['IncomeS1', 'IncomeS2', 'IncomeS3']] == 5).any(axis=1).astype(int)

In [16]:
df_all['ResidenceOwn_dummy'] = (df_all['Own_Resid'] == 1).astype(int)
df_all['ResidenceRent_dummy'] = (df_all['Own_Resid'] == 2).astype(int)
df_all['ResidenceInstitu_dummy'] = (df_all['Own_Resid'] == 3).astype(int)
df_all['ResidenceOthers_dummy'] = (df_all['Own_Resid'] == 4).astype(int)

In [17]:
df_all['ResidInfraPerman_dummy'] = (df_all['Resid_Type'] == 1).astype(int)
df_all['ResidInfraSemi_dummy'] = (df_all['Resid_Type'] == 2).astype(int)
df_all['ResidInfraKachchi_dummy'] = (df_all['Resid_Type'] == 3).astype(int)
df_all['ResidInfraOthers_dummy'] = (df_all['Resid_Type'] == 4).astype(int)

### Dataset building

In [18]:
print(df_all.columns.tolist())

['EcoBelt', 'Prov', 'Rural_Dummy', 'Respon_Female', 'Respon_Age', 'LivingYear', 'Edu_UnderSLC', 'Edu_Certificate', 'Edu_Bachelor', 'Edu_Master', 'Edu_PhD', 'Edu_Literal', 'Edu_Illiterate', 'Edu_year', 'Female_Ratio', 'U18_Ratio', 'A65_Ratio', 'Edu12_Ratio', 'Literal_Ratio', 'Household_memberNum', 'Own_Resid', 'Resid_Type', 'WaterS1', 'WaterS2', 'WaterS3', 'CookFuelS1', 'CookFuelS2', 'CookFuelS3', 'LightEnergy', 'Toilet', 'IncomeS1', 'IncomeS2', 'IncomeS3', 'Remittance_dummy', 'Have_AgriLand', 'Radio_dummy', 'TV_dummy', 'PC_dummy', 'Net_dummy', 'Phone_dummy', 'Mobile_dummy', 'Motorbike_dummy', 'Car_dummy', 'Bike_dummy', 'OtherVehi_dummy', 'Refrige_dummy', 'HouseHead_AgriExpYear', 'SavingMembership', 'RegularSaving', 'OrgMembership', 'AgriSupport', 'Dist_Road', 'Dist_HealthCenter', 'Dist_SecondarySchool', 'Dist_Market', 'Dist_AgriSupport', 'FramMechan', 'CropIncome', 'LivestockIncome', 'NonAgriIncome', 'BusiIncome', 'TotalIncome', 'HeardClimate_Dummy', 'ClimateChanged_Dummy', 'ClimateInfo_Radio', 'ClimateInfo_Telev', 'ClimateInfo_News ', 'ClimateInfo_Aware', 'ClimateInfo_Local', 'ClimateInfo_Neigh', 'ClimateInfo_Famil', 'ClimateInfo_Other', 'ClimateReasonA_Defor', 'ClimateReasonA_Natur', 'ClimateReasonA_Indus', 'ClimateReasonA_Urban', 'ClimateReasonA_Human', 'ClimateReasonA_Godxs', 'ClimateReasonA_Earth', 'ClimateReasonA_Other', 'ClimateReasonA_Donxt', 'ClimateReasonB_Defor', 'ClimateReasonB_Natur', 'ClimateReasonB_Indus', 'ClimateReasonB_Urban', 'ClimateReasonB_Human', 'ClimateReasonB_Godxs', 'ClimateReasonB_Earth', 'ClimateReasonB_Other', 'ClimateReasonC_Defor', 'ClimateReasonC_Natur', 'ClimateReasonC_Indus', 'ClimateReasonC_Urban', 'ClimateReasonC_Human', 'ClimateReasonC_Godxs', 'ClimateReasonC_Earth', 'ClimateReasonC_Other', 'ExpDummyDR', 'ExpDummyFF', 'ExpDummyFS', 'ExpDummyFL', 'ExpDummyIN', 'ExpDummyWS', 'ExpDummyTS', 'ExpDummyHS', 'ExpDummyHR', 'ExpDummySR', 'ExpDummySE', 'ExpDummyLS', 'ExpDummySS', 'ExpDummyAV', 'ExpDummyGLOF', 'ExpDummyHW', 'ExpDummyCW', 'ExpDummyDI', 'ExpDummyOT', 'ImpactDR', 'ImpactFF', 'ImpactFS', 'ImpactFL', 'ImpactIN', 'ImpactWS', 'ImpactTS', 'ImpactHS', 'ImpactHR', 'ImpactSR', 'ImpactSE', 'ImpactLS', 'ImpactSS', 'ImpactAV', 'ImpactGLOF', 'ImpactHW', 'ImpactCW', 'ImpactDI', 'ImpactOT', 'DisasterFoodShortage_DummyDR', 'DisasterFoodShortage_DummyFF', 'DisasterFoodShortage_DummyFS', 'DisasterFoodShortage_DummyFL', 'DisasterFoodShortage_DummyIN', 'DisasterFoodShortage_DummyWS', 'DisasterFoodShortage_DummyTS', 'DisasterFoodShortage_DummyHS', 'DisasterFoodShortage_DummyHR', 'DisasterFoodShortage_DummySR', 'DisasterFoodShortage_DummySE', 'DisasterFoodShortage_DummyLS', 'DisasterFoodShortage_DummySS', 'DisasterFoodShortage_DummyAV', 'DisasterFoodShortage_DummyGLOF', 'DisasterFoodShortage_DummyHW', 'DisasterFoodShortage_DummyCW', 'DisasterFoodShortage_DummyDI', 'DisasterFoodShortage_DummyOT', 'DisasterDie_DummyDR', 'DisasterDie_DummyFF', 'DisasterDie_DummyFS', 'DisasterDie_DummyFL', 'DisasterDie_DummyIN', 'DisasterDie_DummyWS', 'DisasterDie_DummyTS', 'DisasterDie_DummyHS', 'DisasterDie_DummyHR', 'DisasterDie_DummySR', 'DisasterDie_DummySE', 'DisasterDie_DummyLS', 'DisasterDie_DummySS', 'DisasterDie_DummyAV', 'DisasterDie_DummyGLOF', 'DisasterDie_DummyHW', 'DisasterDie_DummyCW', 'DisasterDie_DummyDI', 'DisasterDie_DummyOT', 'DisasterMoneyLoss_DummyDR', 'DisasterMoneyLoss_DummyFF', 'DisasterMoneyLoss_DummyFS', 'DisasterMoneyLoss_DummyFL', 'DisasterMoneyLoss_DummyIN', 'DisasterMoneyLoss_DummyWS', 'DisasterMoneyLoss_DummyTS', 'DisasterMoneyLoss_DummyHS', 'DisasterMoneyLoss_DummyHR', 'DisasterMoneyLoss_DummySR', 'DisasterMoneyLoss_DummySE', 'DisasterMoneyLoss_DummyLS', 'DisasterMoneyLoss_DummySS', 'DisasterMoneyLoss_DummyAV', 'DisasterMoneyLoss_DummyGLOF', 'DisasterMoneyLoss_DummyHW', 'DisasterMoneyLoss_DummyCW', 'DisasterMoneyLoss_DummyDI', 'DisasterMoneyLoss_DummyOT', 'DisasterMoneyLoss_TotalNRsDR', 'DisasterMoneyLoss_TotalNRsFF', 'DisasterMoneyLoss_TotalNRsFS', 'DisasterMoneyLoss_TotalNRsFL', 'DisasterMoneyLoss_TotalNRsIN', 'DisasterMoneyLoss_TotalNRsWS', 'DisasterMoneyLoss_TotalNRsTS', 'DisasterMoneyLoss_TotalNRsHS', 'DisasterMoneyLoss_TotalNRsHR', 'DisasterMoneyLoss_TotalNRsSR', 'DisasterMoneyLoss_TotalNRsSE', 'DisasterMoneyLoss_TotalNRsLS', 'DisasterMoneyLoss_TotalNRsSS', 'DisasterMoneyLoss_TotalNRsAV', 'DisasterMoneyLoss_TotalNRsGLOF', 'DisasterMoneyLoss_TotalNRsHW', 'DisasterMoneyLoss_TotalNRsCW', 'DisasterMoneyLoss_TotalNRsDI', 'DisasterMoneyLoss_TotalNRsOT', 'NewDiseaseCropPast25_Dummy', 'NewInsectCropPast25_Dummy', 'NewDiseaseLivestockPast25_Dummy', 'HumanDiseaseIncreasePast25_Dummy', 'HumanVetorDisIncreasePast25_Dummy', 'HumanWaterDisIncreasePast25_Dummy', 'WaterSourceRiver_IncreaseDummy', 'WaterSourceRiver_DecreaseDummy', 'WaterSourceRiver_DriedDummy', 'WaterSourceSpout_IncreaseDummy', 'WaterSourceSpout_DecreaseDummy', 'WaterSourcePipe_IncreaseDummy', 'WaterSourcePipe_DecreaseDummy', 'Tree_Drop_Dummy', 'Shrub_Drop_Dummy', 'Herbal_Drop_Dummy', 'Grass_Drop_Dummy', 'AquAnimal_Drop_Dummy', 'WildAnimal_Drop_Dummy', 'Birds_Drop_Dummy', 'Insects_Drop_Dummy', 'Shrub_Invasion_Dummy', 'Climber_Invasion_Dummy', 'Creeper_Invasion_Dummy', 'EarlyTree_Dummy', 'LaterTree_Dummy', 'EarlyShrub_Dummy', 'LaterShrub_Dummy', 'EarlyFruit_Dummy', 'LaterFruit_Dummy', 'EarlyHerb_Dummy', 'LaterHerb_Dummy', 'SkillTrainingPast25', 'ChangeCropPatternPast25', 'LeftLandFallow', 'RearedLivestockPAst25', 'SuppIrrigationPast25', 'InvestIrrigationPast25', 'ImprovedSeedPast25', 'ChangePlantingDatePast25', 'IncreaseInorganicFertilizersPAst25', 'IncreaseOrganicFertilizersPAst25', 'NewCropsPast25', 'NewLivestockPast25', 'InvestLivestockPestPast25', 'InsuranceLivestockPast25', 'InsuranceCropPast25', 'FarmingLivestockPast25', 'FarmingCropPast25', 'FarmingLivestockAndCropPast25', 'AgroForestPast25', 'CompatibleCropPast25', 'TunnelFramingPast25', 'ColdStoragePast25', 'SoilWaterConservationPast25', 'VisitClimateOfficePast25', 'FoodConsumptionHabitPast25', 'OfffarmActiPast25', 'NonFarmEmployPast25', 'FamilyMigrationPast25', 'RiskReductionPast25', 'RoadImprovementPast25', 'CommunityPartipationPast25', 'Year', 'EcoBelt_Hill', 'EcoBelt_Mountain', 'EcoBelt_Terai', 'Prov_Bagmati', 'Prov_Gandaki', 'Prov_Karnali', 'Prov_Koshi', 'Prov_Lumbini', 'Prov_Madhesh', 'Prov_Sudurpaschim', 'IncomeResAgri_dummy', 'IncomeResWage_dummy', 'IncomeResNonAgriBusi_dummy', 'IncomeResRemit_dummy', 'IncomeResOthers_dummy', 'ResidenceOwn_dummy', 'ResidenceRent_dummy', 'ResidenceInstitu_dummy', 'ResidenceOthers_dummy', 'ResidInfraPerman_dummy', 'ResidInfraSemi_dummy', 'ResidInfraKachchi_dummy', 'ResidInfraOthers_dummy']

In [ ]:
df_inuse = df_all[[# target and features
                    'SoilWaterConservationPast25', 'RiskReductionPast25', 'RoadImprovementPast25', 'CommunityPartipationPast25',
                    
                    # fearures
                    'ClimateChanged_Dummy', 'HeardClimate_Dummy', 
                   'Respon_Female', 'Respon_Age', 'LivingYear', 'Edu_UnderSLC', 'Edu_Certificate', 
                   'Edu_Bachelor', 'Edu_Master', 'Edu_PhD', 'Edu_Literal', 'Edu_Illiterate', 'Edu_year', # S01
                   'Female_Ratio', 'U18_Ratio', 'A65_Ratio', 'Edu12_Ratio', 'Literal_Ratio', # S02-1
                   'EcoBelt_Hill', 'EcoBelt_Mountain', 'EcoBelt_Terai', 
                   'Prov_Bagmati', 'Prov_Koshi', 'Prov_Lumbini', 'Prov_Madhesh', 'Prov_Sudurpaschim',
                   'Prov_Gandaki', 'Prov_Karnali', # location     
                   'ResidenceOwn_dummy', 'ResidenceRent_dummy', 'ResidenceInstitu_dummy', 'ResidenceOthers_dummy',
                   'ResidInfraPerman_dummy', 'ResidInfraSemi_dummy', 'ResidInfraKachchi_dummy', 'ResidInfraOthers_dummy', # house
                    'Remittance_dummy', 
                   'Have_AgriLand', 'HouseHead_AgriExpYear',
                   'Radio_dummy', 'TV_dummy', 'PC_dummy', 'Net_dummy', 'Phone_dummy',
                   'Mobile_dummy', 'Motorbike_dummy', 'Car_dummy', 'Bike_dummy', 'OtherVehi_dummy', 'Refrige_dummy',
                   'SavingMembership', 'RegularSaving', 'OrgMembership', 'AgriSupport', 
                   'Dist_Road', 'Dist_HealthCenter', 'Dist_SecondarySchool', 'Dist_Market', 'Dist_AgriSupport', 
                   'FramMechan',
                    'IncomeResAgri_dummy', 'IncomeResWage_dummy', 'IncomeResNonAgriBusi_dummy', 'IncomeResRemit_dummy',
                   'IncomeResOthers_dummy', 
                   'CropIncome', 'LivestockIncome', 'NonAgriIncome', 'BusiIncome', 'TotalIncome',
                   'Year',
                   
                   # Awareness sources
                   'ClimateInfo_Radio', 'ClimateInfo_Telev', 'ClimateInfo_News ', 
                   'ClimateInfo_Aware', 'ClimateInfo_Local', 'ClimateInfo_Neigh', 
                   'ClimateInfo_Famil', 'ClimateInfo_Other',
                   
                   # Disaster experiences
                   'ExpDummyDR', 'ExpDummyFF', 'ExpDummyFS', 'ExpDummyFL', 'ExpDummyIN', 'ExpDummyWS', 
                   'ExpDummyTS', 'ExpDummyHS', 'ExpDummyHR', 'ExpDummySR', 'ExpDummySE', 'ExpDummyLS', 
                   'ExpDummySS', 'ExpDummyAV', 'ExpDummyGLOF', 'ExpDummyHW', 'ExpDummyCW', 'ExpDummyDI', 
                   'ExpDummyOT',
                   
                   # DisasterFoodShortage
                   'DisasterFoodShortage_DummyDR', 'DisasterFoodShortage_DummyFF', 'DisasterFoodShortage_DummyFS', 
                   'DisasterFoodShortage_DummyFL', 'DisasterFoodShortage_DummyIN', 'DisasterFoodShortage_DummyWS', 
                   'DisasterFoodShortage_DummyTS', 'DisasterFoodShortage_DummyHS', 'DisasterFoodShortage_DummyHR', 
                   'DisasterFoodShortage_DummySR', 'DisasterFoodShortage_DummySE', 'DisasterFoodShortage_DummyLS', 
                   'DisasterFoodShortage_DummySS', 'DisasterFoodShortage_DummyAV', 'DisasterFoodShortage_DummyGLOF', 
                   'DisasterFoodShortage_DummyHW', 'DisasterFoodShortage_DummyCW', 'DisasterFoodShortage_DummyDI', 
                   'DisasterFoodShortage_DummyOT', 'DisasterDie_DummyDR', 
                   
                   # DisasterDie
                   'DisasterDie_DummyFF', 'DisasterDie_DummyFS', 'DisasterDie_DummyFL', 'DisasterDie_DummyIN', 
                   'DisasterDie_DummyWS', 'DisasterDie_DummyTS', 'DisasterDie_DummyHS', 'DisasterDie_DummyHR', 
                   'DisasterDie_DummySR', 'DisasterDie_DummySE', 'DisasterDie_DummyLS', 'DisasterDie_DummySS', 
                   'DisasterDie_DummyAV', 'DisasterDie_DummyGLOF', 'DisasterDie_DummyHW', 'DisasterDie_DummyCW', 
                   'DisasterDie_DummyDI', 'DisasterDie_DummyOT', 
                   
                   # DisasterMoneyLoss
                   'DisasterMoneyLoss_DummyDR', 'DisasterMoneyLoss_DummyFF', 'DisasterMoneyLoss_DummyFS', 
                   'DisasterMoneyLoss_DummyFL', 'DisasterMoneyLoss_DummyIN', 'DisasterMoneyLoss_DummyWS', 
                   'DisasterMoneyLoss_DummyTS', 'DisasterMoneyLoss_DummyHS', 'DisasterMoneyLoss_DummyHR', 
                   'DisasterMoneyLoss_DummySR', 'DisasterMoneyLoss_DummySE', 'DisasterMoneyLoss_DummyLS', 
                   'DisasterMoneyLoss_DummySS', 'DisasterMoneyLoss_DummyAV', 'DisasterMoneyLoss_DummyGLOF',
                   'DisasterMoneyLoss_DummyHW', 'DisasterMoneyLoss_DummyCW', 'DisasterMoneyLoss_DummyDI', 
                   'DisasterMoneyLoss_DummyOT', 
]]

In [20]:
variname_readable = {'ClimateChanged_Dummy':'Climate Change Awareness Dummy',
                     'HeardClimate_Dummy':'Heard about Climate Change Dummy', 'Respon_Female':'Female Dummy', 
                     'Respon_Age':'Age', 'LivingYear':'Years Living in Community', 'Edu_UnderSLC':'Education under Secondary Certificate Dummy', 
                     'Edu_Certificate':'Education with Secondary Certificate Dummy', 'Edu_Bachelor':'Education with Bachelor Dummy', 
                     'Edu_Master':'Education with Master Dummy',  'Edu_PhD':'Education with PhD Dummy', 
                     'Edu_Literal':'Literate Education Dummy',  'Edu_Illiterate':'Illiterate Dummy', 'Edu_year':'Education Year',
                     'Female_Ratio':'Female Ratio in Household', 'U18_Ratio':'Member Under 18 Ratio', 'A65_Ratio':'Seniors Ratio',
                     'Edu12_Ratio':"Member with 12-Year Education or above Ratio", "Literal_Ratio": "Literate Member Ratio",
                     'EcoBelt_Hill': "EcoBelt Hill Dummy", 'EcoBelt_Mountain': "EcoBelt Mountain Dummy", 'EcoBelt_Terai': "EcoBelt Terai Dummy",
                     'Prov_Bagmati': "Province Bagmati Dummy", 'Prov_Koshi': "Province Koshi Dummy", 'Prov_Lumbini': "Province Lumbibi Dummy",
                     'Prov_Madhesh': "Province Madhesh Dummy", 'Prov_Sudurpaschim': "Province Sudurpaschim Dummy", 'Prov_Gandaki': "Province Gandaki Dummy",
                     'Prov_Karnali': "Province Karnali Dummy",
                     'ResidenceOwn_dummy': "Owned Residence Ownership Dummy", 'ResidenceRent_dummy': 'Rented Residence Ownership Dummy', 
                     'ResidenceInstitu_dummy': 'Institutional Residence Ownership Dummy', 'ResidenceOthers_dummy': 'Other-type Residence Ownership Dummy',
                     'ResidInfraPerman_dummy': 'Permanent Residence Dummy', 'ResidInfraSemi_dummy': 'Semi-Permanent Residence Dummy', 
                     'ResidInfraKachchi_dummy': "Kachchi Residence Dummy", 'ResidInfraOthers_dummy': 'Other Residence Infrastructure Dummy', # house
                     'Remittance_dummy' : "Have Remittance",
                     'Have_AgriLand': "Having Agricultural Land Dummy", 'HouseHead_AgriExpYear': "Household Head Agricultural Experience",
                     'Radio_dummy': "Having Radio Dummy", 'TV_dummy': "Having TV Dummy", 'PC_dummy': "Having Computer Dummy", 'Net_dummy': "Having Internet Dummy",
                     'Phone_dummy': "Having Telephone Dummy", 'Mobile_dummy': "Having Mobile Dummy", 'Motorbike_dummy': "Having Motorbike Dummy", 
                     'Car_dummy': "Having Car Dummy", 'Bike_dummy': "Having Bike Dummy", 'OtherVehi_dummy': "Having Other Vehicle Dummy", 
                     'Refrige_dummy':"Having Refrigator Dummy",
                     'SavingMembership': "Saving Membership Dummy", 'RegularSaving': 'Having Regular Saving Dummy', 
                     'OrgMembership': 'Having Organization Membership Dummy', 'AgriSupport':'Agricultural Supporting Dummy', 
                     'Dist_Road': 'Distance to Motorable Road', 'Dist_HealthCenter': "Distance to Health Center", 
                     'Dist_SecondarySchool': "Distance to Secondary School", 'Dist_Market':"Distance to Market", 'Dist_AgriSupport': 'Distance to Agricultural Center', 
                     'FramMechan':'Farm Mechanization Dummy',
                     'IncomeResAgri_dummy': "Agricultural Income Source Dummy", 'IncomeResWage_dummy': "Wage Income Source Dummy",
                     'IncomeResNonAgriBusi_dummy': "Non-Agricultural Business Income Source Dummy", 'IncomeResRemit_dummy': "Remittance Income Dummy",
                     'IncomeResOthers_dummy': "Others Income Source Dummy", 
                     'CropIncome': "Crop Income", 'LivestockIncome': "Livestock Income", 'NonAgriIncome': "Non-agricultural Income", 
                     'BusiIncome': "Business Income", 'TotalIncome': "Total Income",
                     'Year': "Survey Year",
                                         
                    }

In [ ]:
# ...existing code...
variname_readable.update({
    # Awareness sources
    'ClimateInfo_Radio': "Heard Climate Info from Radio",
    'ClimateInfo_Telev': "Heard Climate Info from Television",
    'ClimateInfo_News ': "Heard Climate Info from Newspaper",
    'ClimateInfo_Aware': "Heard Climate Info from Awareness Program",
    'ClimateInfo_Local': "Heard Climate Info from Local Government",
    'ClimateInfo_Neigh': "Heard Climate Info from Neighbors",
    'ClimateInfo_Famil': "Heard Climate Info from Family",
    'ClimateInfo_Other': "Heard Climate Info from Other Sources",

    # Disaster experiences
    'ExpDummyDR': "Experienced Drought",
    'ExpDummyFF': "Experienced Fire in Forest",
    'ExpDummyFS': "Experienced Forest Fire",
    'ExpDummyFL': "Experienced Flood",
    'ExpDummyIN': "Experienced Insect Infestation",
    'ExpDummyWS': "Experienced Windstorm",
    'ExpDummyTS': "Experienced Thunderstorm",
    'ExpDummyHS': "Experienced Hailstorm",
    'ExpDummyHR': "Experienced Heavy Rain",
    'ExpDummySR': "Experienced Snowfall/Rain",
    'ExpDummySE': "Experienced Earthquake",
    'ExpDummyLS': "Experienced Landslide",
    'ExpDummySS': "Experienced Snowstorm",
    'ExpDummyAV': "Experienced Avalanche",
    'ExpDummyGLOF': "Experienced Glacial Lake Outburst Flood",
    'ExpDummyHW': "Experienced Heat Wave",
    'ExpDummyCW': "Experienced Cold Wave",
    'ExpDummyDI': "Experienced Disease Outbreak",
    'ExpDummyOT': "Experienced Other Disaster",

    # Disaster Food Shortage
    'DisasterFoodShortage_DummyDR': "Food Shortage due to Drought",
    'DisasterFoodShortage_DummyFF': "Food Shortage due to Fire in Forest",
    'DisasterFoodShortage_DummyFS': "Food Shortage due to Fire in Community",
    'DisasterFoodShortage_DummyFL': "Food Shortage due to Flood",
    'DisasterFoodShortage_DummyIN': "Food Shortage due to Inundation",
    'DisasterFoodShortage_DummyWS': "Food Shortage due to Windstorm",
    'DisasterFoodShortage_DummyTS': "Food Shortage due to Thunderstorm",
    'DisasterFoodShortage_DummyHS': "Food Shortage due to Hailstorm",
    'DisasterFoodShortage_DummyHR': "Food Shortage due to Heavy Rain",
    'DisasterFoodShortage_DummySR': "Food Shortage due to Sporadic Rain",
    'DisasterFoodShortage_DummySE': "Food Shortage due to Erosion",
    'DisasterFoodShortage_DummyLS': "Food Shortage due to Landslide",
    'DisasterFoodShortage_DummySS': "Food Shortage due to Snowstorm",
    'DisasterFoodShortage_DummyAV': "Food Shortage due to Avalanche",
    'DisasterFoodShortage_DummyGLOF': "Food Shortage due to GLOF",
    'DisasterFoodShortage_DummyHW': "Food Shortage due to Heat Wave",
    'DisasterFoodShortage_DummyCW': "Food Shortage due to Cold Wave",
    'DisasterFoodShortage_DummyDI': "Food Shortage due to Disease/insect",
    'DisasterFoodShortage_DummyOT': "Food Shortage due to Others",

    # Disaster Die
    'DisasterDie_DummyDR': "Death due to Drought",
    'DisasterDie_DummyFF': "Death due to Fire in Forest",
    'DisasterDie_DummyFS': "Death due to Fire in Community",
    'DisasterDie_DummyFL': "Death due to Flood",
    'DisasterDie_DummyIN': "Death due to Inundation",
    'DisasterDie_DummyWS': "Death due to Windstorm",
    'DisasterDie_DummyTS': "Death due to Thunderstorm",
    'DisasterDie_DummyHS': "Death due to Hailstorm",
    'DisasterDie_DummyHR': "Death due to Heavy Rain",
    'DisasterDie_DummySR': "Death due to Sporadic Rain",
    'DisasterDie_DummySE': "Death due to Erosion",
    'DisasterDie_DummyLS': "Death due to Landslide",
    'DisasterDie_DummySS': "Death due to Snowstorm",
    'DisasterDie_DummyAV': "Death due to Avalanche",
    'DisasterDie_DummyGLOF': "Death due to GLOF",
    'DisasterDie_DummyHW': "Death due to Heat Wave",
    'DisasterDie_DummyCW': "Death due to Cold Wave",
    'DisasterDie_DummyDI': "Death due to Disease/insect",
    'DisasterDie_DummyOT': "Death due to Others",

    # Disaster Money Loss
    'DisasterMoneyLoss_DummyDR': "Money Loss due to Drought",
    'DisasterMoneyLoss_DummyFF': "Money Loss due to Fire in Forest",
    'DisasterMoneyLoss_DummyFS': "Money Loss due to Fire in Community",
    'DisasterMoneyLoss_DummyFL': "Money Loss due to Flood",
    'DisasterMoneyLoss_DummyIN': "Money Loss due to Inundation",
    'DisasterMoneyLoss_DummyWS': "Money Loss due to Windstorm",
    'DisasterMoneyLoss_DummyTS': "Money Loss due to Thunderstorm",
    'DisasterMoneyLoss_DummyHS': "Money Loss due to Hailstorm",
    'DisasterMoneyLoss_DummyHR': "Money Loss due to Heavy Rain",
    'DisasterMoneyLoss_DummySR': "Money Loss due to Sporadic Rain",
    'DisasterMoneyLoss_DummySE': "Money Loss due to Erosion",
    'DisasterMoneyLoss_DummyLS': "Money Loss due to Landslide",
    'DisasterMoneyLoss_DummySS': "Money Loss due to Snowstorm",
    'DisasterMoneyLoss_DummyAV': "Money Loss due to Avalanche",
    'DisasterMoneyLoss_DummyGLOF': "Money Loss due to GLOF",
    'DisasterMoneyLoss_DummyHW': "Money Loss due to Heat Wave",
    'DisasterMoneyLoss_DummyCW': "Money Loss due to Cold Wave",
    'DisasterMoneyLoss_DummyDI': "Money Loss due to Disease/insect",
    'DisasterMoneyLoss_DummyOT': "Money Loss due to Others",
})
# ...existing code...

In [22]:
variname_readable.update({'SoilWaterConservationPast25': 'Soil and Water Conservation Measures in the Past Dummy',
                          'RiskReductionPast25': "Participation in Flood/landslide Risk Reduction and Water Management Practices in the Past Dummy",
                          'RoadImprovementPast25': "Participation in Road and Infrastructure Improvement to Protect from Flood/landslide in the Past Dummy", 
                          'CommunityPartipationPast25':"Participation in Community-based Natural Resource Management Activities in the Past Dummy"})

In [23]:
data_summary = df_inuse.describe().T

In [24]:
data_summary.index = data_summary.index.map(variname_readable)

In [25]:
data_summary.to_excel("MLD01e_Results/Table01_AllData_DataSummary.xlsx")

In [26]:
data_summary

,count,mean,std,min,25%,50%,75%,max
Soil and Water Conservation Measures in the Past Dummy,11568.0,0.210494,0.407677,0.0,0.0,0.0,0.0,1.0
Participation in Flood/landslide Risk Reduction and Water Management Practices in the Past Dummy,11568.0,0.241269,0.427872,0.0,0.0,0.0,0.0,1.0
Participation in Road and Infrastructure Improvement to Protect from Flood/landslide in the Past Dummy,11568.0,0.312673,0.463602,0.0,0.0,0.0,1.0,1.0
Participation in Community-based Natural Resource Management Activities in the Past Dummy,11568.0,0.324602,0.468246,0.0,0.0,0.0,1.0,1.0
Climate Change Awareness Dummy,11568.0,0.901020,0.298648,0.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...
Money Loss due to Heat Wave,11568.0,0.000519,0.022769,0.0,0.0,0.0,0.0,1.0
Money Loss due to Cold Wave,11568.0,0.020228,0.140786,0.0,0.0,0.0,0.0,1.0
Money Loss due to Disease Outbreak,11568.0,0.127161,0.333168,0.0,0.0,0.0,0.0,1.0
Money Loss due to Other Disaster,11568.0,0.000346,0.018593,0.0,0.0,0.0,0.0,1.0
Total Money Loss (NRs) due to Drought,11568.0,8568.913468,71176.716151,0.0,0.0,0.0,0.0,5000000.0